package com.secretlab.exercise.model.vo;

import com.fasterxml.jackson.databind.JsonNode;
import lombok.Data;

/**
 * Response VO for GET /object/{key}. Returned as a full JSON object: { key, value, version,
 * timestamp }. MapStruct populates fields via setters generated by @Data.
 */
@Data
public class KeyValueVO {

  private String key;

  /** Parsed JSON value — rendered as a native JSON object/string in the response. */
  private JsonNode value;

  private int version;

  /** Unix epoch seconds (UTC) of when this version was written. */
  private long timestamp;
}
